jmf_breadcrumbs:

    twig_functions_prefix: 'jmf_'

    breadcrumbs:
        homepage:
            label: 'Home'

        contact:
            label: 'Contact Us'
            parent:
                route: 'homepage'

        terms_and_conditions:
            label: 'Terms & Conditions'
            parent:
                route: 'homepage'

        article.index:
            label: 'Articles'
            parent:
                route: 'homepage'

        article.read:
            label: 'Article'
            parameters:
                id: 'article.id'
            parent:
                route: 'article.index'

        article.submit_comment:
            label: 'Submit comment'
            parameters:
                id: 'article.id'
            parent:
                route: 'article.read'
