services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\Breadcrumbs\:
        resource: '../../'

    Jmf\TemplateRendering\TemplateRendererInterface:
        class: Jmf\TemplateRendering\TemplateRenderer
