services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\Breadcrumbs\:
        resource: '../src/'

    Jmf\TemplateRendering\TemplateRendererInterface:
        class: Jmf\TemplateRendering\TemplateRenderer
