services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\Breadcrumbs\:
        resource: '../src/'
        exclude:
            - '../src/Configuration/BreadcrumbsConfigurationLoader.php'
            - '../src/Definition/'
            - '../src/Exception/'
            - '../src/Repository/'
            - '../src/JmfBreadcrumbsBundle.php'

    Jmf\TemplateRendering\TemplateRendererInterface:
        class: Jmf\TemplateRendering\TemplateRenderer
